### ISSUE TITLE
Amend config to permit json-live-data-server

### ISSUE THREAD

**Issue by evercape** [evercape/hass-resol-KM2#3]
Hi Martin,
I use a VBUS/LAN device and have the json-live-data-server running via HA Addon.
It would be great, if your integration could also handle that.
The json-live-data-server is not protected by username and password. Because these settings in your config dialog are mandatory, I cannot try out if the data format of the json-live-data-server is compatible to the KM2 format.
If I can help adding support for VBUS/LAN please tell me.
Regards
Leo

_Originally posted by @lebetz in https://github.com/evercape/hass-resol-KM2/discussions/1#discussioncomment-7794144_

**Comment by lebetz** [comment]
Hi Martin,
the json-live-data-server returns on endpoint `/cgi-bin/get_resol_device_information`  this data in my case:
[device_info.txt](https://github.com/evercape/hass-resol-KM2/files/13615980/device_info.txt)

The endpoint `/dlx/download/live` returns this json:
[vbus-live.json](https://github.com/evercape/hass-resol-KM2/files/13616012/vbus-live.json)

If I see it correct, then km2 and this endpoint return the same format and it should be enough to just decide which endpoint to use like in the original code: https://github.com/dm82m/hass-Deltasol-KM2/blob/1bcb26b45dc04be2a7aa90405bc1e313d01be864/custom_components/deltasol/deltasolapi.py#L140-L166
Regards
Leo

**Comment by evercape** [comment]
Thanks Leo, I will check it out tomorrow/over the weekend. Much appreciated for providing the device information and JSON data.
M

**Comment by evercape** [comment]
Hi Leo,

I am on Christmas family holidays, only have Laptop, no mouse, no external keyboard, no big screen.....so not ideal...

The following might work:

In [resolapi.py](https://github.com/evercape/hass-resol-KM2/blob/main/custom_components/resol/resolapi.py#L113) line 113 add this method:

    def fetch_data_dlx(self):
        response = {}

        url = f"http://{self.host}/dlx/download/live"
        _LOGGER.debug(f"{self.device['serial']}: DLX requesting sensor data from url {url}")

        response = requests.request("GET", url)

        if(response.status_code == 200):
            response_data = response.json()

        _LOGGER.debug(f"DLX response: {response}")

        # Proceed to parsing
        return self.__parse_data(response_data)


In [sensor.py](https://github.com/evercape/hass-resol-KM2/blob/main/custom_components/resol/sensor.py#L66) line 66 add the following:

       if device_check["product"] == "KM2":
            data = await hass.async_add_executor_job(resol_api.fetch_data_km2)
        elif device_check["product"] == "KM1":
            data = await hass.async_add_executor_job(resol_api.fetch_data_km1)
        elif device_check["product"] == "DL2" or device_check["product"] == "DL3":
            data = await hass.async_add_executor_job(resol_api.fetch_data_dlx)

In [config_flow](https://github.com/evercape/hass-resol-KM2/blob/main/custom_components/resol/config_flow.py#L54) line 54 add the following:

        if device["product"] == "KM2":
            auth_check = await hass.async_add_executor_job(resol_api.fetch_data_km2)
        elif device["product"] == "KM1":
            auth_check = await hass.async_add_executor_job(resol_api.fetch_data_km1)
        elif device["product"] == "DL2" or device["product"] == "DL3":
            auth_check = await hass.async_add_executor_job(resol_api.fetch_data_dlx)

I think it would be best to expose your JSON data for testing via a public IP or DYNDNS, even on Proxmox that might work? If not, I will setup a better test environment when back from holidays, which is only middle of January.

Let me know if the above works, maybe it does.

Thanks
Martin

**Comment by lebetz** [comment]
Hi Martin,
thanks alot. I only had to add a `:{self.port}` to the url. And the line to change in resolapi.py was 133 and not 113.
But after these two small changes, it works like a charme.
All Sensors are created correctly.
Regards
Leo

**Comment by evercape** [comment]
> `:{self.port}`

...can't believe I forgot that, sorry bout that.

Glad it worked.

I am still not happy with it - I think some people on the json live data server may require username/password and even API key from what I can see.

If you do get a chance to make your setup public (even just whitelist for me) I would like to integrate it and test it properly.

Also with proper exceptions, logging etc. and once properly tested upgrade to a new version of this custom integration.

Pls send me a screenshot how the device looks like if you do get a moment.

Thanks for helping with testing this integration, much appreciated.

Rgds
Martin

**Comment by evercape** [comment]
@lebetz 

Hi Leo,

Embarrassing that it took me so long to update this.

Can you pls pull the latest files from MASTER and check that your DL2 device is working?

I have added the code exactly as per above, including the `:{self.port}` which I had forgotten.

Here is the update:
https://github.com/evercape/hass-resol-KM2/commit/19ee10d0e579b4cfdf0dba9ddbb639c63fe8d659

Please let me know if everything is working fine, then we can close this issue/request. 

Thanks
Martin

**Comment by evercape** [comment]
@lebetz Hi Leo - pls let me know then I can close this issue and update a version. Thanks Martin

**Comment by lebetz** [comment]
Hello @evercape ,
sorry for late reply. It works with the master branch now. Thanks alot.
Please publish a new release so that I can install the component via HACS.

**Comment by evercape** [comment]
Thanks @lebetz just published new version [2024.09.1](https://github.com/evercape/hass-resol-KM2/releases/tag/2024.09.1)

Thanks for your help
M.

**Comment by lebetz** [comment]
Hi @evercape ,
I just found out that there is still a problem:
In this line, there is still hard coded a call to km2 api: https://github.com/evercape/hass-resol-KM2/blob/52cc93f6d377cc5b83dff3ef76d4049c2c4ec825/custom_components/resol/sensor.py#L133
That fails in my case.
I replaced the line with the same code as in async_setup_entry (https://github.com/evercape/hass-resol-KM2/blob/52cc93f6d377cc5b83dff3ef76d4049c2c4ec825/custom_components/resol/sensor.py#L52-L70).
That works fine for me. But I'm not sure if that is a good solution.

**Comment by evercape** [comment]
@lebetz thanks for this. I do remember this branching into various devices had to happen twice, and I somehow forgot this. I amended the master branch. if you could do an install from that and let me know if this works for you? then I will commit to new version as well. thanks Martin

**Comment by lebetz** [comment]
Hi @evercape ,
thanks for the fast response. I assume you have to change the variable name to "full_data" in you commit to get it working. Sorry, I forgot that in my post.
https://github.com/evercape/hass-resol-KM2/commit/a4bcd9a2ee692062311c007f9c9fa6c6feea00c9

**Comment by evercape** [comment]
Sorry I am on holiday, no big screen only small laptop and forgot my glasses. typical. can you pls post me what works for you? with the "full_data" then I can just copy and paste. otherwise will do when back home Oct 7

**Comment by evercape** [comment]
@lebetz sorry for such a long silence, been traveling. Updated master can you pls check that everything is working fine? https://github.com/evercape/hass-resol-KM2/commit/c7bef6ba8a3a5f19356bdd9c883bcda187a25a68 thanks Martin

**Comment by evercape** [comment]
Have published version 2024.11.0 which includes the above update. thanks @lebetz for helping out here!
