### ISSUE TITLE
Still not available on hacs

### ISSUE THREAD

**Issue by Felix-Jan** [evercape/hass-resol-KM2#5]
Last update should have solved the issue of not showing the integration on hacs. However, searching for "_Resol_Controller" or any part of that does not show the expected  result in the list. Only the older variant of  dm82m/hass-Deltasol-KM2 is listed. 

**Expected behavior**
I expected the integration to be listed in HACS when searching for resol

**Comment by Felix-Jan** [comment]
![image](https://github.com/evercape/hass-resol-KM2/assets/116590685/b8679b73-5c57-4808-81dd-d8018f8d8c6f)

**Comment by evercape** [comment]
Hi Felix,

Thanks I am aware of it and flagged it [here](https://github.com/hacs/default/pull/2179#pullrequestreview-1887308073).

I am very new to this and don't understand what is going on.

Have you got a. better understanding?

Thanks for your help.
Martin

**Comment by evercape** [comment]
On another note, you can install it as a custom repo by just copying the link. Its just not that great as I did publish it to HACS.

**Comment by Felix-Jan** [comment]
> On another note, you can install it as a custom repo by just copying the link. Its just not that great as I did publish it to HACS.

Thanks for the tip. It is working now! Great functionality what you made; just what I was looking for!
I am new on HA and github, so in the first phase of trying to get understanding of all. So, I am the wrong person to ask for help on this one...

Thanks, Felix.

**Comment by evercape** [comment]
Thanks Felix, happy you like it. First time for me to program in Python and do something on HACS, Github etc. as well.

**Comment by Holgi72** [comment]
Hello, 
I have the same issue as Felix-Jan. I can't find it in HACS.  I checked this link
https://github.com/hacs/default/pull/2179#pullrequestreview-1887308073
Sry, how can I install it? 
Thanks

**Comment by evercape** [comment]
> Hello, I have the same issue as Felix-Jan. I can't find it in HACS. I checked this link [hacs/default#2179 (review)](https://github.com/hacs/default/pull/2179#pullrequestreview-1887308073) Sry, how can I install it? Thanks

Sorry about this. I been out of action for a while, will try to re-submit to HACS.

You can manually install by referencing this repository: https://github.com/evercape/hass-resol-KM2

If you want to try and add a custom repository to HACS do the following:
Go to any of the sections (integrations, frontend, automation).
Click on the 3 dots in the top right corner.
Select "Custom repositories"
Add the URL to the repository.
Select the correct category.
Click the "ADD" button.

**Comment by Holgi72** [comment]
Hello, 
I try, but there is written.. see pic below
![Unbenannt](https://github.com/evercape/hass-resol-KM2/assets/159046635/79a202bf-7d36-473a-bc27-a15c58504cf3)

**Comment by Holgi72** [comment]
Thanks, works. Thanks for these tool!

**Comment by evercape** [comment]
Great to know it's working. I really struggle with HACS and once I am back mid July from holidays will look into this again.

**Comment by evercape** [comment]
Finally its available in HACS - you need to search for **RESOL CONTROLLER**

![image](https://github.com/user-attachments/assets/285d2918-29f5-4898-90d2-863da4bb7f9c)
