### ISSUE TITLE
HACS isn´t working

### ISSUE THREAD

**Issue by wagnerpizza** [evercape/hass-resol-KM2#6]
Hi,

I installed the Hac and edited the sensor.py with host, username and password.
What do I have to acitvate on configuration.yaml?

1. Problem, which password and username is the right one. There are two stickers on the back of KM2 for
- Webinterface access
- for SSH

2. I am using py instead of yaml first time. Do I have to add the information only in sensor.py and saving?
You wrote it will run out of the box on KM2 but it doesn't with my instance.

Would be nice if someone could help me out.

**Comment by evercape** [comment]
Hi there,

You need to install the component via HACS or directly as a custom component, then activate it.

Once that is done, no need to modify `sensor.py` or any of the scripts.

Follow these [instructions](https://github.com/evercape/hass-resol-KM2?tab=readme-ov-file#step-1---connection-details) to enter the details in the UI.

If you still have issues, DM me and I will help you via screen sharing. 

With regards to the username/password on the KM2 its the web interface - see screenshot.
![image](https://github.com/user-attachments/assets/294f6792-25b5-4fa0-9ce1-4ea1457587fa)



Thanks
Martin

**Comment by wagnerpizza** [comment]
Hi Martin, thanks now it works. I used the wrong HACS (your inspiration). My fault

**Comment by wagnerpizza** [comment]
Everything works like described

**Comment by evercape** [comment]
> Everything works like described

Glad you got it working. M
